INSERT INTO PERSONNAGE_PRINCIPAL (type_personnage, nom_personnage, relation_reveur, personnage_fictif, personnage_réel, id_reveur) VALUES
('mentor', 'Alex Martin', 'famille', 0, 0, 1),
('inconnu', 'Charlie Lemoine', 'ami proche', 0, 0, 2),
('guide spirituel', 'Orion le renard', 'totem', 0, 0, 3),
('inconnu', 'Morgan Chevalier', 'amour', 1, 0, 4),
('ennemi', 'Riley Lemoine', 'amour', 1, 0, 5),
('inconnu', 'Jordan Durand', 'ami proche', 1, 0, 6),
('inconnu', 'Taylor Petit', 'ami proche', 1, 0, 7),
('ami', 'Morgan Petit', 'famille', 1, 1, 8),
('guide spirituel', 'Tigrou le chat', 'totem', 1, 1, 9),
('ennemi', 'Emilia Moreau', 'amour', 1, 1, 10),
('mentor', 'Riley Martin', 'amour', 1, 0, 11),
('ami', 'Emilia Garnier', 'collègue', 0, 0, 12),
('guide spirituel', 'Plume le serpent', 'créature récurrente', 0, 0, 13),
('rival', 'Casey Chevalier', 'famille', 1, 1, 14),
('inconnu', 'Riley Garnier', 'amour', 0, 1, 15),
('mentor', 'Riley Garnier', 'famille', 1, 1, 16),
('mentor', 'Riley Dupont', 'ami proche', 1, 1, 17),
('inconnu', 'Riley Chevalier', 'amour', 1, 1, 18),
('créature du rêve', 'Shadow le hibou', 'symbole', 1, 0, 19),
('mentor', 'Taylor Bernard', 'étranger', 1, 1, 20),
('animal de compagnie', 'Tigrou le hibou', 'animal domestique', 1, 0, 21),
('créature du rêve', 'Misty le chien', 'animal domestique', 0, 0, 22),
('mentor', 'Casey Dupont', 'amour', 0, 1, 23),
('inconnu', 'Taylor Rousseau', 'famille', 0, 0, 24),
('inconnu', 'Sam Rousseau', 'famille', 1, 1, 25),
('rival', 'Taylor Martin', 'amour', 1, 0, 26),
('guide spirituel', 'Plume le renard', 'symbole', 0, 1, 27),
('mentor', 'Jordan Durand', 'ancien camarade', 0, 1, 28),
('rival', 'Emilia Moreau', 'amour', 0, 0, 29),
('ami', 'Lucas Moreau', 'étranger', 1, 0, 30),
('rival', 'Emilia Lemoine', 'ami proche', 1, 1, 31),
('gardien', 'Shadow le renard', 'symbole', 1, 0, 32),
('ami', 'Morgan Moreau', 'ancien camarade', 0, 1, 33),
('créature du rêve', 'Pixel le hibou', 'animal domestique', 0, 1, 34),
('mentor', 'Morgan Dupont', 'amour', 1, 1, 35),
('gardien', 'Coco le serpent', 'créature récurrente', 1, 1, 36),
('inconnu', 'Emilia Rousseau', 'ancien camarade', 1, 0, 37),
('inconnu', 'Alex Petit', 'ancien camarade', 0, 1, 38),
('inconnu', 'Riley Bernard', 'étranger', 1, 1, 39),
('ennemi', 'Sam Durand', 'collègue', 0, 1, 40),
('ennemi', 'Casey Moreau', 'amour', 0, 1, 41),
('mentor', 'Morgan Martin', 'famille', 0, 0, 42),
('ennemi', 'Taylor Martin', 'famille', 1, 1, 43),
('gardien', 'Coco le chien', 'totem', 0, 1, 44),
('inconnu', 'Sam Durand', 'ancien camarade', 0, 0, 45),
('inconnu', 'Emilia Rousseau', 'ami proche', 1, 0, 46),
('rival', 'Sam Lemoine', 'famille', 0, 0, 47),
('inconnu', 'Alex Rousseau', 'ancien camarade', 0, 1, 48),
('ami', 'Casey Dupont', 'étranger', 0, 1, 49),
('ami', 'Morgan Petit', 'collègue', 1, 0, 50),
('mentor', 'Riley Moreau', 'étranger', 1, 0, 51),
('inconnu', 'Morgan Moreau', 'famille', 0, 0, 52),
('animal de compagnie', 'Pixel le corbeau', 'symbole', 1, 0, 53),
('rival', 'Lucas Dupont', 'famille', 1, 0, 54),
('ennemi', 'Sam Durand', 'amour', 1, 0, 55),
('ennemi', 'Taylor Petit', 'collègue', 1, 1, 56),
('mentor', 'Morgan Dupont', 'famille', 0, 0, 57),
('animal de compagnie', 'Tigrou le serpent', 'symbole', 0, 1, 58),
('inconnu', 'Casey Durand', 'ami proche', 1, 0, 59),
('rival', 'Charlie Dupont', 'étranger', 0, 0, 60),
('rival', 'Jordan Bernard', 'ancien camarade', 1, 0, 61),
('rival', 'Sam Martin', 'amour', 0, 0, 62),
('inconnu', 'Charlie Petit', 'ami proche', 0, 0, 63),
('ami', 'Alex Garnier', 'amour', 0, 1, 64),
('inconnu', 'Casey Petit', 'étranger', 0, 0, 65),
('gardien', 'Rex le hibou', 'totem', 0, 1, 66),
('inconnu', 'Alex Chevalier', 'famille', 0, 0, 67),
('rival', 'Sam Chevalier', 'collègue', 0, 1, 68),
('ennemi', 'Casey Moreau', 'ami proche', 0, 0, 69),
('ami', 'Emilia Bernard', 'ancien camarade', 0, 0, 70),
('animal de compagnie', 'Pixel le chat', 'créature récurrente', 1, 1, 71),
('ami', 'Sam Durand', 'ami proche', 1, 1, 72),
('animal de compagnie', 'Plume le corbeau', 'créature récurrente', 1, 1, 73),
('créature du rêve', 'Shadow le chien', 'créature récurrente', 1, 1, 74),
('rival', 'Morgan Garnier', 'amour', 1, 1, 75),
('inconnu', 'Morgan Chevalier', 'ancien camarade', 0, 1, 76),
('rival', 'Alex Moreau', 'étranger', 1, 1, 77),
('rival', 'Alex Garnier', 'étranger', 1, 0, 78),
('mentor', 'Jordan Martin', 'collègue', 0, 0, 79),
('ami', 'Casey Rousseau', 'ami proche', 1, 0, 80),
('mentor', 'Emilia Garnier', 'collègue', 0, 1, 81),
('gardien', 'Tigrou le renard', 'animal domestique', 1, 0, 82),
('rival', 'Jordan Moreau', 'famille', 0, 0, 83),
('créature du rêve', 'Luna le hibou', 'créature récurrente', 0, 1, 84),
('ami', 'Alex Rousseau', 'étranger', 1, 0, 85),
('rival', 'Alex Moreau', 'collègue', 1, 1, 86),
('mentor', 'Sam Rousseau', 'étranger', 1, 0, 87),
('mentor', 'Lucas Martin', 'famille', 1, 1, 88),
('rival', 'Sam Garnier', 'étranger', 1, 0, 89),
('ami', 'Lucas Garnier', 'ami proche', 1, 0, 90),
('rival', 'Lucas Petit', 'ami proche', 0, 1, 91),
('mentor', 'Morgan Bernard', 'amour', 0, 0, 92),
('mentor', 'Morgan Petit', 'collègue', 1, 0, 93),
('inconnu', 'Emilia Moreau', 'ami proche', 1, 1, 94),
('mentor', 'Riley Dupont', 'étranger', 1, 0, 95),
('ennemi', 'Charlie Moreau', 'collègue', 1, 0, 96),
('rival', 'Alex Lemoine', 'collègue', 1, 1, 97),
('mentor', 'Casey Rousseau', 'étranger', 1, 0, 98),
('rival', 'Alex Bernard', 'collègue', 1, 0, 99),
('ennemi', 'Alex Moreau', 'collègue', 1, 0, 100),
('mentor', 'Jordan Garnier', 'famille', 1, 0, 101),
('créature du rêve', 'Luna le corbeau', 'symbole', 1, 0, 102),
('ami', 'Casey Rousseau', 'famille', 0, 1, 103),
('inconnu', 'Casey Martin', 'ancien camarade', 0, 0, 104),
('guide spirituel', 'Coco le corbeau', 'animal domestique', 1, 0, 105),
('gardien', 'Orion le renard', 'symbole', 0, 1, 106),
('rival', 'Taylor Moreau', 'ancien camarade', 1, 0, 107),
('inconnu', 'Casey Chevalier', 'famille', 0, 1, 108),
('inconnu', 'Casey Moreau', 'étranger', 0, 1, 109),
('ennemi', 'Casey Garnier', 'famille', 0, 1, 110),
('inconnu', 'Casey Dupont', 'étranger', 0, 1, 111),
('inconnu', 'Charlie Petit', 'famille', 1, 1, 112),
('ami', 'Casey Garnier', 'collègue', 1, 1, 113),
('mentor', 'Sam Bernard', 'étranger', 0, 0, 114),
('mentor', 'Casey Rousseau', 'étranger', 0, 1, 115),
('ennemi', 'Morgan Martin', 'famille', 1, 1, 116),
('mentor', 'Emilia Bernard', 'famille', 0, 0, 117),
('animal de compagnie', 'Pixel le hibou', 'totem', 1, 1, 118),
('mentor', 'Taylor Durand', 'ancien camarade', 0, 0, 119),
('mentor', 'Taylor Garnier', 'ami proche', 0, 1, 120),
('ennemi', 'Taylor Moreau', 'famille', 0, 1, 121),
('animal de compagnie', 'Plume le corbeau', 'symbole', 1, 0, 122),
('rival', 'Casey Bernard', 'ancien camarade', 0, 1, 123),
('gardien', 'Shadow le hibou', 'créature récurrente', 1, 0, 124),
('ami', 'Lucas Dupont', 'amour', 0, 0, 125),
('inconnu', 'Lucas Dupont', 'étranger', 0, 0, 126),
('ennemi', 'Morgan Martin', 'amour', 1, 1, 127),
('inconnu', 'Charlie Chevalier', 'amour', 0, 1, 128),
('ami', 'Sam Dupont', 'collègue', 1, 0, 129),
('ami', 'Jordan Rousseau', 'amour', 1, 0, 130),
('rival', 'Lucas Bernard', 'ami proche', 1, 1, 131),
('inconnu', 'Morgan Dupont', 'famille', 1, 0, 132),
('rival', 'Morgan Chevalier', 'amour', 0, 0, 133),
('ennemi', 'Jordan Martin', 'collègue', 1, 1, 134),
('inconnu', 'Sam Rousseau', 'famille', 0, 0, 135),
('mentor', 'Sam Durand', 'collègue', 1, 1, 136),
('inconnu', 'Lucas Garnier', 'ancien camarade', 1, 1, 137),
('inconnu', 'Morgan Moreau', 'ami proche', 1, 0, 138),
('inconnu', 'Lucas Petit', 'ancien camarade', 1, 1, 139),
('rival', 'Morgan Lemoine', 'collègue', 1, 0, 140),
('rival', 'Alex Garnier', 'ami proche', 0, 0, 141),
('ennemi', 'Morgan Lemoine', 'ami proche', 0, 0, 142),
('ennemi', 'Taylor Dupont', 'famille', 1, 0, 143),
('créature du rêve', 'Simba le chat', 'symbole', 1, 0, 144),
('mentor', 'Charlie Bernard', 'amour', 0, 1, 145),
('mentor', 'Sam Martin', 'collègue', 1, 0, 146),
('mentor', 'Sam Dupont', 'amour', 0, 1, 147),
('ennemi', 'Sam Bernard', 'amour', 1, 1, 148),
('ami', 'Taylor Bernard', 'étranger', 1, 0, 149),
('ami', 'Riley Durand', 'ami proche', 0, 0, 150),
('mentor', 'Emilia Garnier', 'famille', 1, 0, 151),
('ami', 'Jordan Rousseau', 'amour', 0, 1, 152),
('inconnu', 'Alex Durand', 'collègue', 1, 0, 153),
('animal de compagnie', 'Simba le renard', 'animal domestique', 1, 1, 154),
('mentor', 'Alex Chevalier', 'ancien camarade', 0, 1, 155),
('rival', 'Lucas Petit', 'amour', 1, 1, 156),
('ami', 'Taylor Petit', 'ami proche', 0, 1, 157),
('rival', 'Emilia Rousseau', 'étranger', 1, 0, 158),
('mentor', 'Charlie Petit', 'ancien camarade', 0, 0, 159),
('gardien', 'Luna le chien', 'créature récurrente', 0, 1, 160),
('animal de compagnie', 'Plume le hibou', 'animal domestique', 0, 0, 161),
('guide spirituel', 'Coco le chat', 'animal domestique', 1, 1, 162),
('mentor', 'Charlie Rousseau', 'collègue', 0, 1, 163),
('animal de compagnie', 'Orion le chat', 'créature récurrente', 1, 1, 164),
('ami', 'Taylor Garnier', 'collègue', 0, 0, 165),
('ennemi', 'Charlie Petit', 'famille', 0, 1, 166),
('ami', 'Morgan Moreau', 'étranger', 1, 0, 167),
('mentor', 'Morgan Durand', 'collègue', 0, 0, 168),
('mentor', 'Sam Moreau', 'collègue', 1, 1, 169),
('rival', 'Jordan Rousseau', 'famille', 0, 0, 170),
('ami', 'Morgan Moreau', 'amour', 1, 0, 171),
('ami', 'Riley Chevalier', 'étranger', 1, 1, 172),
('ami', 'Riley Garnier', 'ancien camarade', 1, 0, 173),
('créature du rêve', 'Simba le chat', 'créature récurrente', 0, 0, 174),
('guide spirituel', 'Pixel le serpent', 'symbole', 0, 1, 175),
('ami', 'Charlie Moreau', 'ancien camarade', 1, 1, 176),
('guide spirituel', 'Shadow le chat', 'totem', 0, 1, 177),
('gardien', 'Shadow le serpent', 'totem', 1, 0, 178),
('inconnu', 'Alex Chevalier', 'étranger', 1, 0, 179),
('rival', 'Emilia Bernard', 'collègue', 1, 0, 180),
('ami', 'Lucas Martin', 'collègue', 1, 0, 181),
('inconnu', 'Casey Dupont', 'collègue', 1, 1, 182),
('rival', 'Alex Durand', 'ancien camarade', 0, 1, 183),
('ennemi', 'Emilia Chevalier', 'amour', 1, 1, 184),
('ami', 'Emilia Lemoine', 'étranger', 0, 1, 185),
('ennemi', 'Jordan Chevalier', 'étranger', 1, 0, 186),
('créature du rêve', 'Tigrou le chien', 'symbole', 1, 1, 187),
('créature du rêve', 'Shadow le serpent', 'animal domestique', 1, 1, 188),
('ennemi', 'Morgan Moreau', 'amour', 0, 1, 189),
('ennemi', 'Morgan Garnier', 'étranger', 1, 0, 190),
('rival', 'Charlie Bernard', 'famille', 1, 0, 191),
('animal de compagnie', 'Tigrou le serpent', 'totem', 0, 1, 192),
('mentor', 'Riley Rousseau', 'amour', 1, 1, 193),
('créature du rêve', 'Luna le chien', 'animal domestique', 1, 0, 194),
('ami', 'Morgan Garnier', 'collègue', 0, 1, 195),
('gardien', 'Pixel le chat', 'totem', 1, 1, 196),
('rival', 'Jordan Petit', 'amour', 0, 1, 197),
('mentor', 'Morgan Rousseau', 'amour', 0, 1, 198),
('ennemi', 'Casey Chevalier', 'ami proche', 0, 1, 199),
('rival', 'Morgan Dupont', 'amour', 1, 1, 200);
